Cargo.toml, README.md, src/internals/mod.rs, src/internals/query_params_store.rs, src/lib.rs, src/test_request.rs, src/test_server.rs, src/test_server/server_shared_state.rs, test.sh
* Add `TestRequest::add_query_params`
* Add `TestRequest::add_query_param`
* Add `TestRequest::clear_query_params`
* Add `TestServer::add_query_params`
* Add `TestServer::add_query_param`
* Add `TestServer::clear_query_params`
Adds the ability to send query parameters.
=> Feat query params

src/test_request.rs, src/test_response.rs
* Add `TestResponse::form`
* Add tests for `TestResponse::json` and `TestResponse::text`.
=> feat: TestResponse::form

src/test_response.rs
* `TestResponse::bytes` is changed to `TestResponse::as_bytes`, and returns `bytes::Bytes` over `&[u8]`.
* Add `TestResponse::into_bytes`
* Add `From` definition for converting `TestResponse` into `Bytes`
This is a bunch of breaking changes to improve the bytes conversions for the response.
One can now chose to consume or borrow the underlying bytes, and it's been changed from a `u8` slice to a `Bytes` object.
=> feat: change bytes conversions for response

.gitignore, src/into_test_server_core.rs, src/lib.rs, src/test_request.rs, src/test_response.rs, src/test_server.rs, src/test_server_config.rs
* Make doc links shorter and more readable.
* Update documentation on fail fast behaviour.
=> Docs adjust links

src/internals/starting_tcp_setup.rs, src/test_request.rs, src/test_server.rs, src/test_server/server_shared_state.rs, src/util/new_random_tcp_listener.rs
* Add `TryFrom<TestRequest>` to convert into a `http::Request`.
=> feat: TryFrom<TestRequest> for http::Request

Cargo.toml, README.md
* fix incorrect import in README.md
=> Fix readme

Cargo.toml
* Bump for releasing docs readme change.
=> chore: bump cargo version

Cargo.toml, src/test_response.rs
* Add `TestResponse::assert_status_forbidden` method.
=> feat: add TestResponse::assert_status_forbidden

Cargo.toml, README.md, src/test_response.rs
* Fix expected to be on the left of the assertions provided.
* Add support to use pretty_assertions crate.
=> feat: add pretty assertions

Cargo.toml, src/test_request.rs, src/test_response.rs
* Asserts now include method and url.
* Standardised text for many responses.
=> feat: improve error messages

Cargo.toml, src/internals/transport_layer/http_transport_layer.rs
* Update all dependencies to latest (except Hyper and HTTP)
=> chore: bump dependencies

Cargo.toml, src/transport_layer/into_transport_layer.rs
* Update to the latest dependencies.
I'm releasing this as a minor bump, as there are minor bumps in dependencies.
=> chore: update dependencies to latest

Cargo.toml, examples/example-todo/main.rs, src/lib.rs, src/multipart/mod.rs, src/multipart/multipart_form.rs, src/multipart/part.rs, src/test_request.rs
* add `TestRequest::multipart`
This adds multipart form support.
=> feat: multipart support

Cargo.toml
=> chore: remove unused rand dependency

Cargo.toml
* Fix link on crates io to docs
=> fix: docs link in crates io

Cargo.toml, README.md, test.sh
* Version bump for msgpack.
* Change to test msgpack along side other features.
* Add links to msgpack and yaml information in readme.
Big thanks to @pitbuster for adding support!
=> chore: version bump for new msgpack version

Cargo.toml, src/lib.rs, src/multipart/mod.rs, src/test_request.rs
* Upgrade `serde_yaml` to latest.
* Fix yaml / msgpack docs mixup.
* Fix features not showing on docs.rs.
* Fix docs.rs feature warning being missing.
=> chore: upgrade yaml version and fix docs

Cargo.toml, src/lib.rs, src/test_request.rs
* Version bump for release.
* Add test on sending expired cookies to the cookie integration tests section.
This is to release the fix by @lasantosr from #69 .
=> chore: version bump

Cargo.toml
* Upgrade dependencies to latest.
* Drop patch versions.
=> chore: upgrade dependencies

README.md
=> docs: add thanks to readme

Cargo.toml
* Minor patch bump for releasing doc change.
=> chore: 14.9.1 patch bump

Cargo.toml, README.md
* Update README with version information.
* Bump msgpack dependency.
=> chore: bump msgpack dependency

Cargo.toml, src/lib.rs
* add crate features to docs.rs.
=> docs: add crate features to docs.rs

README.md, examples/example-todo/README.md, examples/example-websocket-chat/README.md, examples/example-websocket-ping-pong/README.md
* Tweak readme layouts for examples and main crate.
=> fix: improve readme layouts

Cargo.toml, src/internals/transport_layer/mock_transport_layer.rs, src/test_server.rs, src/transport_layer/transport_layer.rs
* `TransportLayer` now requires `Sync`.
* `TestServer` is now `Sync`.
Fixes #86
=> feat: make TestServer Sync

Cargo.toml, README.md, examples/example-shuttle/README.md, examples/example-shuttle/main.rs, examples/example-websocket-chat/main.rs, examples/example-websocket-ping-pong/main.rs, test.sh
* add example of using Shuttle with Axum Test
This is the todo application with the Shuttle wrapper added.
=> feat: add shuttle example

Cargo.toml, src/test_response.rs
* add `TestRequest::assert_status_payload_too_large`
* add `TestRequest::assert_status_unprocessable_entity`
* add `TestRequest::assert_status_too_many_requests`
* add `TestRequest::assert_status_service_unavailable`
=> feat: add more TestRequest::assert_status_* methods

Cargo.toml, src/test_response.rs
* add `TestResponse::contains_header`
* add `TestResponse::assert_contains_header`
* add `TestResponse::assert_status_see_other`
=> Feat more assert improvements

src/test_response.rs
* add TestResponse::assert_header
=> feat: TestResponse::assert_header

Cargo.toml, examples/example-websocket-chat/main.rs, src/internals/query_params_store.rs, src/internals/request_path_formatter.rs, src/internals/starting_tcp_setup.rs, src/internals/transport_layer/http_transport_layer.rs, src/test_request.rs, src/test_server.rs, src/transport_layer/into_transport_layer.rs, src/transport_layer/into_transport_layer/axum_service.rs, src/transport_layer/into_transport_layer/into_make_service.rs, src/transport_layer/into_transport_layer/into_make_service_with_connect_info.rs, src/transport_layer/into_transport_layer/router.rs, src/transport_layer/into_transport_layer/shuttle_axum.rs, src/transport_layer/transport_layer.rs, src/transport_layer/transport_layer_builder.rs, src/util/mod.rs, src/util/new_random_tcp_listener.rs, src/util/new_random_tokio_tcp_listener.rs, src/util/serve_handle.rs, src/util/spawn_serve.rs
* add `util::spawn_serve`
* refactor code to utilise `util::spawn_serve`
* simplify internal tcp logic
=> feat: util::spawn_serve

Cargo.toml, src/internals/transport_layer/mock_transport_layer.rs, src/transport_layer/into_transport_layer/into_make_service.rs, src/transport_layer/transport_layer.rs
* change `std::marker::Sync` to `Sync`
* add compilation test
* bump to v15.7.1
=> chore: v15.7.1

Cargo.toml, src/test_response.rs
* bump to v15.7.2
* add example for `TestResponse::assert_json_from_file`
=> chore: bump to v15.7.2 for releasing assert_json_from_file

Cargo.toml, files/example.yaml, src/test_response.rs
* add method TestResponse::assert_yaml_from_file
* refactor assert_json_from_file into own module
=> feat: TestResponse::assert_yaml_from_file

Cargo.toml, src/internals/format_status_code_range.rs, src/internals/mod.rs, src/internals/try_into_range_bounds.rs, src/test_response.rs
* add `TestResponse::assert_status_in_range`
* add `TestResponse::assert_status_not_in_range`
Add assertions for ranges of statuses.
=> feat: assert status in and out of range

src/internals/expected_state.rs, src/internals/query_params_store.rs, src/multipart/part.rs, src/test_request.rs, src/test_response.rs
* Add more tests for Parts, QueryParamsStore, TestRequest, and TestResponse.
This gets total test coverage up to around 82%.
=> chore: tests

src/test_response.rs
* add `TestResponse::assert_status_conflict` method
This is to extend the TestResponse::assert_status_* methods.
=> feat: add assert status conflict

Cargo.toml
=> chore: bump version to 16.2

Cargo.toml
* Add required features for the examples that need them.
Fixes #121
=> feat: add required features for examples

Cargo.toml, src/internals/debug_response_body.rs, src/internals/mod.rs, src/test_response.rs
* Now outputs the body of the request on assert responses.
implement #123
=> Feat body formatting

test.sh
* Add a test to ensure nightly support stays.
Test for #133
=> feat: add nightly test

Cargo.toml, docs.sh, src/expect_json.rs, src/lib.rs, src/test_response.rs
* add public `expect_json` support.
=> feat: expect json

Cargo.toml, README.md
* Bump to release version of expect-json
=> chore: bump expect-json version

README.md
* Fixes a typo in README.md
I saw the typo and I figured I'd make the change instead of reporting it as an issue.
=> Fix typo Compatability -> Compatibility in README.md

Cargo.toml
* Bump to version 18.1.0 for release.
=> chore: bump version to 18.1.0
