JosephLenton/axum-test

Cargo.toml, README.md, src/test_server.rs, src/test_server_config.rs, src/util/new_random_socket_addr.rs
* Change default IP address from `0.0.0.0` to `127.0.0.1`.
* Add means to change defautt IP.
* Add means to change default Port.
* Remove default socket address.
* Bump to version 8.
This fixes Windows support, and if needed by the user, gives the ability to set _only_ the IP to use.
=> fix: windows support

Cargo.toml, src/into_test_server_core.rs, src/lib.rs, src/test_server.rs
* Refactor `TestServer` to take something that implements `IntoTestServerThread`.
* Add `IntoTestServerThread` type for modelling how to build from `IntoMakeService` and `IntoMakeServiceWithConnectInfo`.
=> feat: add means for building using IntoMakeServiceWithConnectInfo

src/test_request.rs, src/test_response.rs
Implements the change as described in https://github.com/JosephLenton/axum-test/issues/7
Will conflict somewhat with https://github.com/JosephLenton/axum-test/pull/8, but opening now as a proof-of-concept.
Closes #7
=> assert methods take self by reference

Cargo.toml, README.md, src/test_request.rs, src/test_response.rs
* Change default expect behaviour to expect 2xx range or not, rather than 200 alone.
* Add `#[track_caller]` to assert functions.
=> fix: 200 fail status

src/lib.rs, src/test_request.rs
* Added builder methods `add_header` and `clear_headers` to the struct `TestRequest`
Fixes #12 
In case of duplicate headers (e.g. setting the `content-type`) the last ones take precedence. I think this is the less surprising outcome, although maybe it is better to substitute `TestRequest.headers` with some map.
=> Added support for adding arbitrary header to a `TestRequest`

Cargo.toml, src/test_request.rs, src/test_response.rs
* Improve the error message for assert_status_success and assert_status_failure.
=> fix: better error messages for status code failure

Cargo.toml, src/lib.rs, src/test_response.rs, src/test_server.rs, src/test_server_config.rs
* Allow requests that include the full http schema, to bypass the TestServer.
This is needed for a real world E2E test.
=> Feat http requests

src/test_response.rs
* Change to use `DeserializeOwned` over `for<'a>` requirements
There should be no real difference here. The change is done to make the code slightly more readable.
=> refactor: change deserialize requirements to deserializeowned

README.md, examples/example-todo/main.rs, src/lib.rs, src/test_request.rs, src/test_request/test_request_config.rs, src/test_server.rs, src/test_server_config.rs
* The `TestRequest` failure expectation behaviour is now disabled by default.
* Expect success behaviour can now be turned through the `TestServerConfig`
=> change: default expect failure

src/test_request.rs, src/test_server.rs, src/util/mod.rs, src/util/new_random_socket_addr.rs, src/util/reserved_port.rs
* reserve ports whilst in use.
Fixes a bug where two ports can sometimes be picked at the same time.
=> fix: reserve ports whilst the TestServer is running

Cargo.toml, src/internals/expected_state.rs, src/internals/mod.rs, src/test_request.rs, src/test_request/test_request_config.rs, src/test_server.rs
* add `TestServer::expect_success()`
* add `TestServer::expect_failure()`
This adds two functions to the `TestServer` which are present in the config, and the `TestRequest`. It is to make the API more uniform.
=> feat: server expect success and failure

src/test_request.rs
=> refactor: fix typo in test name

Cargo.toml, src/internals/mod.rs, src/internals/request_path_formatter.rs, src/test_request.rs, src/test_request/test_request_config.rs, src/test_response.rs, src/test_server.rs, src/test_server_config.rs
* Move Method + path information into common `RequestPathFormatter` .
* Update `TestRequest` errors to include the requested path.
This is a continuing refactor to make all of the error messages similar and use the same common information across the board.
=> Feat request format tidyup

Cargo.toml, src/internals/starting_tcp_setup.rs, src/transport_layer/into_transport_layer/into_make_service.rs, src/util/new_random_socket_addr.rs, src/util/new_random_tcp_listener.rs
* Upgrade the port reserve crate to the latest version, to fix IP reservation bug.
The reserve-port crate is using an unspecified IP, and Axum Test is using Localhost. This can cause a port to be offered which isn't available.
=> fix: upstream port reserving bug

Cargo.toml, src/multipart/mod.rs, src/multipart/multipart_form.rs, src/multipart/part.rs, src/test_request.rs
* Add documentation for `multipart::MultipartForm` and `multipart::Part`.
=> docs: add more documentation on multipart form and parts

Cargo.toml, README.md, src/multipart/mod.rs, src/multipart/multipart_form.rs, src/multipart/part.rs, src/test_request.rs, src/test_response.rs, test.sh
* Add Yaml support for sending, receiving, and asserting.
Yaml support is behind the `yaml` feature flag.
=> feat: add Yaml support

Cargo.toml, README.md, src/test_request.rs, src/test_response.rs, test.sh
* Adds support for sending, receiving and asserting [MsgPack](https://msgpack.org/) content
Support is behind the `msgpack` flag. I didn't bump the crate version, but if it needed I am happy to do it.
=> feat: add MsgPack support

Cargo.toml, src/internals/query_params_store.rs, src/test_request.rs, src/test_server.rs, src/test_server/server_shared_state.rs
Add escape hatches to add query params without url encoding:
* Add `TestServer::add_raw_query_param`
* Add `TestRequest::add_raw_query_param`
=> feat: add_raw_query_param

Cargo.toml, src/test_request.rs, src/test_server.rs, src/test_server/server_shared_state.rs, src/test_server_config.rs, src/test_server_config_builder.rs
* Add `TestServer::scheme()`
* Add `TestRequest::scheme()`
One can now set the scheme (i.e. http or https) made on requests.
=> feat: scheme

src/test_request.rs
* skip expired cookies when sending requests
Closes #68, by skipping expired cookies when sending requests instead of removing them from the jar, so that they can be asserted.
=> Skip expired cookies

src/test_server.rs
* Fix doc comment of `TestServer::server_address()`
`Transport::HttpRandomPort` ➡️ `Transport::HttpIpPort`
=> docs: fix document of `TestServer::server_address()`

Cargo.toml, src/internals/with_this_mut.rs, src/test_server.rs, src/test_server/server_shared_state.rs, src/transport_layer/transport_layer.rs
* `TransportLayer` now requires `Send`, this allows being created inside a `OnceCell` and other types.
=> fix: make `TransportLayer` sendable

Cargo.toml, README.md, src/internals/query_params_store.rs, src/internals/request_path_formatter.rs, src/internals/transport_layer/http_transport_layer.rs, src/internals/transport_layer/mock_transport_layer.rs, src/lib.rs, src/test_request.rs, src/test_request/test_request_config.rs, src/test_response.rs, src/test_server.rs, src/transport_layer/transport_layer.rs, test.sh
* Rewrite of route path to allow query parameters in requests. i.e. `server.get("/users?limit=10")`
* Add support for `axum-extra` `TypedPath`
=> feat: TypedRoute support

Cargo.toml, src/test_request.rs, src/test_response.rs, src/test_web_socket.rs
* Add `TestResponse::assert_text_contains`
* Add `TestWebSocket::assert_receive_text_contains`
* Add `TestRequest::authorization`
* Add `TestRequest::authorization_bearer`
Adding a few nice utility functions.
=> feat: extra utility functions for requests and responses

src/util/mod.rs, src/util/new_random_tcp_listener.rs, src/util/new_random_tokio_tcp_listener.rs
* add `util::new_random_tokio_tcp_listener`
* add `util::new_random_tokio_tcp_listener_with_socket_addr`
This adds Tokio versions of building a `TcpListener`. This is useful as the Tokio variants are actually what we want when using Axum.
=> feat: generate random tokio::net::TcpListener

Cargo.toml, README.md, src/lib.rs, src/transport_layer/into_transport_layer.rs, src/transport_layer/into_transport_layer/axum_service.rs, src/transport_layer/into_transport_layer/into_make_service.rs, src/transport_layer/into_transport_layer/into_make_service_with_connect_info.rs, src/transport_layer/into_transport_layer/router.rs, src/transport_layer/into_transport_layer/shuttle_axum.rs, test.sh
This adds support for building a `TestServer` from Shuttle.
* `TestServer` can be built from `shuttle_axum::ShuttleAxum`.
* `TestServer` can be built from `shuttle_axum::AxumService`.
=> feat: add support for building TestServer from Shuttle

examples/example-todo/main.rs, examples/example-websocket-chat/main.rs, examples/example-websocket-ping-pong/main.rs
* fix examples. Change `build_app` to `build_server`.
I had renamed this in a previous commit and must have missed these examples.
=> fix: change build_app to build_server in examples

Cargo.toml, src/test_request.rs, src/test_response.rs, src/test_server.rs
These are some quality of life changes to improve working with headers, and simplify header code.
* `TestServer::add_header` can now take a wider array of types for the name and value, and converts internally.
* `TestRequest::add_header` can now take a wider array of types for the name and value, and converts internally.
* `TestResponse::maybe_header` can now take a wider array of types for the name, and converts internally.
* `TestResponse::header` can now take a wider array of types for the name, and converts internally.
* `TestResponse::iter_headers_by_name` can now take a wider array of types for the name, and converts internally.
* `TestResponse::contains_header` can now take a wider array of types for the name, and converts internally.
* `TestResponse::assert_contains_header` can …
=> feat: header methods can now take many values

Cargo.toml, src/internals/transport_layer/mock_transport_layer.rs, src/transport_layer/into_transport_layer.rs, src/transport_layer/into_transport_layer/into_make_service.rs, src/transport_layer/into_transport_layer/into_make_service_with_connect_info.rs, src/transport_layer/transport_layer.rs, src/util/spawn_serve.rs
* `IntoMakeService` support for transport layer is generic.
* `IntoMakeServiceWithConnectInfo` support for transport layer is generic.
This PR allows an `IntoMakeService` which holds any `Router` like service. Including ones that wrap a `Router`.
fixes #105
=> feat: make into service generic

src/internals/transport_layer/mock_transport_layer.rs, src/transport_layer/into_transport_layer/into_make_service.rs, src/transport_layer/transport_layer.rs
when using TestServer in tokio::sync::OnceCell Sync trait is required. in last version it was removed for some reasons which was a breaking change.
=> fix: add std::marker::Sync trait in TransportLayer

Cargo.toml, README.md, examples/example-websocket-chat/main.rs, src/lib.rs, src/test_request.rs, src/test_server.rs, src/test_web_socket.rs, src/transport_layer/into_transport_layer.rs, src/transport_layer/into_transport_layer/into_make_service_with_connect_info.rs, src/transport_layer/into_transport_layer/serve.rs, src/transport_layer/into_transport_layer/with_graceful_shutdown.rs, src/util/spawn_serve.rs, test.sh
WIP: this requires dependencies to be updated to Axum 8 first.
* Updates to use Axum 8.
Fixes #129
=> feat: update to Axum 8

Cargo.toml, README.md
* Remove a mention to Shuttle from the Readme.
=> docs: remove shuttle reference on readme

Cargo.toml, README.md, src/internals/debug_response_body.rs, src/internals/query_params_store.rs, src/internals/starting_tcp_setup.rs, src/internals/websockets/test_response_websocket.rs, src/multipart/multipart_form.rs, src/multipart/part.rs, src/test_request.rs, src/test_response.rs, src/test_web_socket.rs, src/transport_layer/transport_layer_builder.rs, test.sh
* Update dependencies to the latest.
* Require Rust 1.83
* Add `multipart::Part::add_header`
Fixes #141
=> feat: add multipart::Part::add_header
